- op: replace
  path: /spec/replicas
  value: 2

- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      path: /hea
      port: 443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 10