crds:
# -- Install and upgrade CRDs
  install: true
global:
  image:
    tag: ""
  # See https://github.com/argoproj/argo-helm/issues/1984
  deploymentStrategy:
    type: RollingUpdate
dex:
  enabled: false
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    paths:
      - /
configs:
  params:
    server.insecure: false
    #server.basehref: /argocd
    # -- Used if Argo CD is running behind reverse proxy under subpath different from /
    #server.rootpath: '/argocd'