apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: kustmyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"  # Replace with your application's port
    spec:
      containers:
      - name: my-app
        #image: nginx
        image: abhijitdocker87/aspapphello:v1.0
        ports:
        - containerPort: 80  # Add this line to specify the container port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"