- op: replace
  path: /spec/replicas
  value: 3

- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      path: /
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10